config/routes.rb
DemoMagazine::Application.routes.draw do
  root :to => "articles#index"
  get '/articles/:article_id/comments/:parent_id' => 'comments#new', as: "reply"
  resources :articles do
    resources :comments 

  end
  resources :users, :only => [:new,:edit,:create,:update]
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :title,:body
	belongs_to :user
	has_and_belongs_to_many :categories
	has_many :comments, -> {where("comment_id == ?",0)}
	scope :published, lambda { where("articles.published_at IS NOT NULL") }
	scope :draft, lambda { where("articles.published_at IS NULL") }
	scope :recent, lambda { published.where("articles.published_at > ?",
1.week.ago.to_date) }
	scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
	def published?
      published_at.present?
    end
    def owned_by?(owner)
		return false unless owner.is_a?(User)
		user == owner
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
	default_scope -> {order('name')}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
		
	validates_presence_of :name,:email,:body
	validate :article_should_be_published
	belongs_to :article
	has_many :comments
	belongs_to :comment
	def article_should_be_published
		errors.add(:article_id, "is not published yet") if article && !article.published?
	end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	validates_uniqueness_of :email
	validates_length_of :email, :within => 5..50
	#validates_format_of :email, :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i
	validates_confirmation_of :password
	has_one :profile
	has_many :articles,  -> { order('published_at DESC, title ASC')},:dependent => :destroy
	has_many :replies, through: :articles, source: :comments
	before_save :encrypt_new_password
 
	def self.authenticate(email, password)
		user = find_by_email(email)
		return user if user && user.authenticated?(password)
	end
	 
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	protected

	def encrypt_new_password
		return if password.blank?
		self.hashed_password = encrypt(password)
	end

	def password_required?
		hashed_password.blank? || password.present?
	end

	def encrypt(string)
		Digest::SHA1.hexdigest(string)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 protected
# Returns the currently logged in user or nil if there isn't one
	def current_user
	return unless session[:user_id]
	@current_user ||= User.find_by_id(session[:user_id])
	end
# Make current_user available in templates as a helper
helper_method :current_user
# Filter method to enforce a login requirement
# Apply as a before_action on any controller you want to protect
	def authenticate
	logged_in? || access_denied
	end
# Predicate method to test for a logged in user
	def logged_in?
	current_user.is_a? User
	end
# Make logged_in? available in templates as a helper
helper_method :logged_in?
	def access_denied
	redirect_to login_path, notice: "Please log in to continue"
	return false
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :published_at, :location)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_article, :except => :destroy
    before_filter :authenticate, :only => :destroy


	def new
	 @comment = @article.comments.new(:comment_id => params[:parent_id])
	end
	def create
		@comment = @article.comments.new(comment_params)
		@comment.comment_id = params[:comment][:comment_id]

		#render :text => params[:comment].to_yaml and return

		if @comment.save
		redirect_to @article, notice: 'Thanks for your comment'
		else
		redirect_to @article, alert: 'Unable to add comment'
		end
	end

	def destroy
		@article = current_user.articles.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		respond_to do |format|
            format.html { redirect_to @article, notice: 'Comment Deleted' }
            format.js
		end
	end

	private
	def load_article
		@article = Article.find(params[:article_id])
	end

	def comment_params
		params.require(:comment).permit(:name, :email, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
	if user = User.authenticate(params[:email], params[:password])
	session[:user_id] = user.id
	redirect_to root_path, :notice => "Logged in successfully"
	else
	flash.now[:alert] = "Invalid login/password combination"
	render :action => 'new'
	end
end
def destroy
reset_session
redirect_to root_path, :notice => "You successfully logged out"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate, only: [:edit, :update]
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	def new
		@user = User.new
	end


	def create
		@user = User.new(user_params)
		if @user.save
		redirect_to articles_path, notice: 'User successfully added.'
		else
		render action: :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
		redirect_to articles_path, notice: 'Updated user information successfully.'
		else
		render action: 'edit'
		end
	end

	private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
<h3>
<%= link_to article.title, article %>
<% if article.owned_by? current_user %>
<span class='actions'>
<%= link_to "Edit", edit_article_path(article) %>
<%= link_to "Delete", article, confirm: "Are you sure?", method: :delete %>
</span>
<% end %>
</h3>
<%= article.body %>
<% end %> 

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<div id="articles">
<%= render @articles %>
</div>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>
<h3>Comments</h3>
<div id="comments">
<%= render @article.comments %>
</div>
<%= link_to "new comment", new_article_comment_path(@article, :format => :js),
:remote => true, :id => 'new_comment_link' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>

<h3>
<%= comment.name %> &lt;<%= comment.email %>&gt;:
<% if @article.owned_by? current_user and comment.comments.empty? %>
<span class='actions'>
<%#= link_to 'Delete', article_comment_path(:article_id => @article,
:id => comment), confirm: 'Are you sure?', method: :delete , remote: true %>
</span>
<% end %>
</h3>
<%= comment.body %>

    <p><%= link_to 'Add a Reply', reply_path(@article,:parent_id => comment.id) %></p>
    <% unless comment.comments.empty? %>
      <ul class="nested_comment">
        <%= render comment.comments %>
      </ul>
    <% end %>

<% end %> 

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").remove()

app/views/comments/new.html.erb
<%= form_for([@article, @comment]) do |f| %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
<%= f.hidden_field :comment_id %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :body %><br />
<%= f.text_area :body %>
</div>
<div class="actions">
<%= f.submit 'Add' %>
</div>
<% end %>

app/views/comments/new.js.erb
$("<%= escape_javascript render(file: 'comments/new.html.erb') %>").insertAfter('#comments');
$('#new_comment').hide().slideDown();
$('#new_comment_link').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
	<h1><%= link_to "Magazine", root_path %></h1>
	<div id="user_bar">
	<% if logged_in? %>
	<%= link_to "New Article", new_article_path %> |
	<%= link_to "Edit Password", edit_user_path(current_user) %> |
	<%= link_to "Logout", logout_path %>
	<% else %>
	<%= link_to "Login", login_path %>
	<%= link_to "Sign In", new_user_path %>
	<% end %>
	</div>
<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
<%= yield %>
<div id="footer">
A simple magazine practice

</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@article) do |f| %>
<h1>Edit user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %> 

app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %> 